[package]
name = "browser-container"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
axum = "0.8.8"
chromiumoxide = "0.8.0"
futures = "0.3.31"
port_check = "0.3.0"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
